sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t navanithbs/react_ecom_website -f Dockerfile.dev .

script:
  - docker run -e CI=true navanithbs/react_ecom_website npm run test
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted <access-key-id>="
  secret_access_key:
    secure: "Encypted <secret-access-key>="
  region: "us-east-2"
  app: "NKMS_Ecom"
  env: "Nkmsecom-env"
  bucket_name: "react-ecom-nkms"
  